.TH "/home/adrien/Documents/testFactory/include Directory Reference" 3 "Wed Nov 27 2013" "Version 1.0" "Stickman Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/adrien/Documents/testFactory/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDecorator\fP"
.br
.ti -1c
.RI "directory \fBFactory\fP"
.br
.ti -1c
.RI "directory \fBSingleton\fP"
.br
.ti -1c
.RI "directory \fBStrategy\fP"
.br
.in -1c
