.TH "include/Factory/AFactory.h" 3 "Wed Nov 27 2013" "Version 1.0" "Stickman Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Factory/AFactory.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFactory\fP"
.br
.RI "\fIProvide a factory to create blocks\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stickman Project from the source code\&.
