.TH "include/Decorator/Cape.h" 3 "Wed Nov 27 2013" "Version 1.0" "Stickman Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Decorator/Cape.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCape\fP"
.br
.RI "\fI\fBCape\fP upgrade\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stickman Project from the source code\&.
