.TH "Shoes" 3 "Wed Nov 27 2013" "Version 1.0" "Stickman Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shoes \- 
.PP
\fBShoes\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAUpgrade\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShoes\fP (\fBPlayer\fP *character, int posX, int posY)"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "virtual \fB~Shoes\fP ()"
.br
.RI "\fIDefault destructor\&. \fP"
.ti -1c
.RI "virtual int \fBgetJumpSpeed\fP ()"
.br
.RI "\fIGet the jumping speed value\&. \fP"
.ti -1c
.RI "virtual int \fBgetJumpHeight\fP ()"
.br
.RI "\fIGet the jumping height value\&. \fP"
.ti -1c
.RI "virtual int \fBgetSpeed\fP ()"
.br
.RI "\fIGet the speed value\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBShoes\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
Adrien Bodineau and Alexandre Gomes 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shoes::Shoes (\fBPlayer\fP *character, intposX, intposY)"

.PP
Default constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcharacter\fP Decorated character 
.br
\fIposX\fP Position x 
.br
\fIposY\fP Position y 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Shoes::getJumpHeight ()\fC [virtual]\fP"

.PP
Get the jumping height value\&. 
.PP
\fBReturns:\fP
.RS 4
Jumping height value 
.RE
.PP

.PP
Reimplemented from \fBPlayer\fP\&.
.SS "int Shoes::getJumpSpeed ()\fC [virtual]\fP"

.PP
Get the jumping speed value\&. 
.PP
\fBReturns:\fP
.RS 4
Jump speed value 
.RE
.PP

.PP
Reimplemented from \fBPlayer\fP\&.
.SS "int Shoes::getSpeed ()\fC [virtual]\fP"

.PP
Get the speed value\&. 
.PP
\fBReturns:\fP
.RS 4
Speed value 
.RE
.PP

.PP
Reimplemented from \fBPlayer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stickman Project from the source code\&.
